name: Lighthouse
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: treosh/lighthouse-ci-action@v2
        with:
          budgetPath: ./lighthouse-budget.json
          configPath: ./lighthouse.json
          runs: 3
          temporaryPublicStorage: true
          urls: |
            https://vuemu.netlify.com
#            PR_NUMBER is only available on 'pull_request' and Nelify would have to build first
#            https://deploy-preview-$PR_NUMBER--vuemu.netlify.com/
        env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
#           PR_NUMBER: ${{ github.event.pull_request.number }}

#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 10.x
#       - run: |
#           npm install
#           npm run build
#       - run: |
#           npm install -g @lhci/cli@0.3.x
#           lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
