name: CI

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: [push]
#   push:
#     branches: [ master ]
#  pull_request:
#     branches: [ master ]

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  build:
    runs-on: ubuntu-latest
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: dep install and app build
      run: |
        yarn install
        yarn build
